### ISSUE TITLE
Not working on GKE

### ISSUE THREAD

**Issue by ekoome** [intel/multus-cni#106]
I have followed the README but i can not get the sample networks working on GKE. 

1. Created the CRD and configs
2. built and copied the binaries on GKE node

3. created multus config file on the node.
```
/etc/cni/net.d/00-multus-cni.conf
{
    "name": "node-cni-network",
    "type": "multus",
    "kubeconfig": "/etc/kubernetes/node-kubeconfig.yaml"
}
```

BTW - What should be the contents of this file?  /etc/kubernetes/node-kubeconfig.yaml. It does not exist on my node. No details on the README.

4. added the right annotations onto the pod.
5. Checked ifconfig a and there are no new interfaces on the pod.

Does anyone have a working gist for GKE? Also how do i debug. Checked node logs and I cannot see anything on multus.

**Comment by dougbtv** [comment]
Hey @ekoome -- that `"kubeconfig": "/etc/kubernetes/node-kubeconfig.yaml"` points to the Kubernetes configuration on each node, this will have the authentication for the `system:node` user.

If that's specified but, not available as a file -- Multus won't have a way to authenticate with the API, so it'll fail to pull up the CRD objects you have defined.

**Comment by ekoome** [comment]
Thanks Doug.
Do you have an example node-kubeconfig file? Is this created automatically in a node and so it is a case of finding where it is in my node?

If so, where does gke keep its node Kube configs ?

For logging, what should I be looking for? Kubelet logs are verbose.

Lastly, the last step for restarting kubelet, do I need to pass KUBELET_OPTS for cni & cni dir or does kubelet have these enabled by default?

**Comment by rkamudhan** [comment]
@ekoome Can you check `~/.kube` folder in the GKE nodes ? I used the GKE lot back. That folder should have the kubeconfig data to communicate to the `master` from the `node`.

**Comment by ekoome** [comment]
Tried kubeconfig at /var/lib/kube-proxy/kubeconfig but not working.

Checked kubelet logs and I cannot see any error messages related to multus.

My thoughts on this, what actually calls multus. Nothing in the setup links multus to kubelet or am I missing something.

**Comment by ekoome** [comment]
Thanks rkamudhan. 
I have created the credentials on the node the kubectl works. Referenced the credentials in multus.conf, but still unable to get it to work. On a separate note, why can't multus authenticate with the node service account which is already configured in the VM? Also not clear how multus gets invoked as it is not running as a daemon.

As a general question, if only interested in macvlan, do i need multus? i cannot see any tutorial on configuring macvlan without multus on a cloud provider.

**Comment by rkamudhan** [comment]
@ekoome It should works, because the kubeconfig is the mechanism to make the authentication for out-of-cluster communication. I believe something is missing in your env. 

In order to overcome it, my suggestion is to use [multus-daemonset.yml](https://github.com/intel/multus-cni/blob/master/images/multus-daemonset.yml) developed by @dougbtv . It is should be using in-cluster communication as developed @dcbw . So by using Multus daemonset you can overcome the issue of GKE.

Please edit the https://github.com/intel/multus-cni/blob/master/images/multus-daemonset.yml#L78 according to your requirement.

Follow the steps in https://github.com/intel/multus-cni#quickstart-guide

**Comment by rkamudhan** [comment]
@ekoome Any Luck ?

**Comment by Mierdin** [comment]
I looked into this, and managed to get multus installed and the configuration in place using the daemonset deployment instructions. However, GKE starts the kubelets with `kubenet` instead of CNI by default. The only supported configuration that uses CNI would be to use the NetworkPolicy and Calico integration. In **theory** you could do that, then manually reconfigure to use multus instead, but AFAICT this would be blown away during any upgrades, and you'd have to make sure you do it on any new nodes that GKE spins up for you. Not to mention this is in pretty shady territory support-wise.

For me, this isn't really worth it, and was enough to convince me to go back to DIY kubernetes instead of GKE. YMMV.

**Comment by dougbtv** [comment]
@ekoome -- could you close this issue? Otherwise, can we restart the conversation here to see if we can address any concerns you might have? Thanks!

**Comment by s1061123** [comment]
@ekoome hi. Is there any update on the issue?
It is quite a long time to hold issue, so let me close this issue once. Please re-open or create another issue if you still have. Thanks.
