### ISSUE TITLE
Feature Request: Support multiple networks for kubernetes default network (previous title: Primary pod IP)

### ISSUE THREAD

**Issue by ep4eg** [intel/multus-cni#158]
The summary is in https://github.com/intel/multus-cni/issues/158#issuecomment-426345674 (added by @s1061123 )

--------- original comment ------
I'm currently using kube-router's network as default and attaching additional interfaces as objects, is there any chance to select as a primary IP not the default one? Time to time I need to have attached interface as primary.

**Comment by s1061123** [comment]
@ep4eg I am not sure that 'select as a primary IP' and 'primary IP' itself. Could you please add some examples (network attachment yaml, pod yaml and some command outputs: 'ip -d a' if possible)?

**Comment by ep4eg** [comment]
@s1061123 In other words, I got something like
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "kubernetes",
          "ips": [
              "<IP>"
          ],
          "default": true,
          "dns": {}
      },{
          "name": "macvlan-conf",
          "interface": "net1",
          "ips": [
              "<IP>"
          ],
          "mac": "<MAC>",
          "dns": {}
      }]
```
As you can see k8s considers kube-router interface (which is default network), as default and "net1" interface attached as "NetworkAttachmentDefinition"

here's the manifest

```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "<if_name>",
      "mode": "bridge",
      "isDefaultGateway":false,
      "ipam": {
        "type": "host-local",
        "subnet": "<subnet>",
        "rangeStart": "<r_start>",
        "rangeEnd": "<r_end>",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "<gw>"
      }
    }'
```
  The question: Is there any way to tell k8s that macvlan interface is default? I wanna see an IP address of attached MACVLAN interface as a service endpoint.

  So, here's another CNI configuration file

```   {
    "name": "multus-cni-network",
    "type": "multus",
    "cniVersion": "0.3.0",
    "kubeconfig": "/etc/kubernetes/admin.conf",
    "delegates": [{
            "bridge": "kube-bridge",
            "ipam": {
                    "subnet": "<subnet>",
                    "type": "host-local",
                    "routes": [
                        { "dst": "<cluster_subnet>" }
                    ],
                    "gateway": "<gw>"
            },
            "isDefaultGateway": true,
            "hairpinMode": true,
            "name": "kubernetes",
            "type": "bridge"
        }]
}
```

P.S. as I realized, that's not possible.

**Comment by s1061123** [comment]
@ep4eg So confirmation. In /etc/cni/net.d/foobar.conf (or your conf), you wrote kube-router CNI for delegate, correct?

Currently multus-cni always use 'the first item of delegate field' as default network (i.e. k8s uses it as pod address as well as k8s API traffic).
So how about to replace it (kube-router with macvlan)?

Multus team is also trying to introduce use CRD name in /etc/cni/net.d/foobar.conf, just FYI.

**Comment by ep4eg** [comment]
@s1061123 I don't really need macvlan interface in every single pod.

**Comment by Elegant996** [comment]
Experiencing the same issue. A use case is when you want to force the pod to communicate over a pre-existing VPN client sitting on your firewall (pfSense or similar).

The issue is that if `kube-router` is the default then any traffic on `net0` appears to be limited to its subnet as it has no proper routes.

`multus` should for the default to be overridden via the annotations section of the pod. Perhaps similar to:

`k8s.v1.cni.cncf.io/networks-default: macvlan-conf`

This should force the default listed in `/etc/cni/net.d/foobar.conf` to be `net0` in order to maintain communications. This may require additional routing tables though.

**Comment by s1061123** [comment]
@ep4eg So in your case, you want to have multiple 'default k8s network' in case of pod at whole cluster, correct (i.e Pod1 uses macvlan to talk to k8s network but Pod2 uses vlan)? 
It is not supported for now. Multus-cni expects one network for default network and it expects all pods uses one network.

So it seems to be feature request for multus. Can I change subject as feature request and add some description for that?

**Comment by Elegant996** [comment]
Feature request is fine but I wouldn't say we need multiple default networks. As per @ep4eg's original post, we have few instances where one of two pods in a cluster may require `macvlan` to be the default instead of `kube-router`. We're not looking to assign a `macvlan` interface to every pod.

In these cases, we seek to have all non-cluster-related communication to go out over `macvlan` as the default route.

I have been successful in establishing the setup by using [Scenario 2 of this guide](http://www.allgoodbits.org/articles/view/24) but this requires a script on start up in order to achieve since we cannot define routing tables currently (`go` does support them though).

**Comment by s1061123** [comment]
@Elegant996, I mean it from cluster point of view. Under cluster, some pod uses macvlan for default network and some of them uses another. Correct?

**Comment by Elegant996** [comment]
Yep. Thanks!

**Comment by ep4eg** [comment]
@s1061123 correct.

Actually, there is one more question - Delegate to default network works fine, but once I use multiple interfaces configuration I get martian packets on both interfaces. That's definitely routing issue, so seems `multus` doesn't work out of the box.

**Comment by s1061123** [comment]
@ep4eg thanks! BTW, regarding the last stuff seems to be routing issue. From network point of view, multus-cni does not touch routing/addressing. Multus-cni just giving the interface to provide multi CNI based network invocation. Some (well actually almost I guess) cni plugin does not expect to work with other cni plugin simultaneously so it should be further discussion of somewhere else.
Multiple interface/network is, still now, a kind of frontier ;)

**Comment by s1061123** [comment]
So summary:

- Add a feature to add multiple networks for kubernetes network (i.e. for api-server and Pod IP), and
- Allows user to specify which network is used for each pod

To solve the issue, we may discuss about multiple default network for kubernetes is still valid or not because currently kubernetes expects to connect to pods in one network.

**Comment by Elegant996** [comment]
This issue may need to extend upstream to the CNI plugins or perhaps CNI itself so that it supports routing tables.

Would it be preferable for `multus` to create the extra routing table or should the `ipam` plugin create it if it is specified? The parameter would take an integer but would default to `main` or 254 which is what it currently uses.

**Comment by Elegant996** [comment]
@ep4eg I'm not sure if our situations are identical but I'll leave this work around for you. Take the case below where I added a `macvlan` with a a name of `net1` and static IP of `10.0.30.30`. You would then create an initContainer with NET_ADMIN rights and mount your `rt_tables` in order to add additional routing tables and routes.

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rtorrent-conf
data:
  routing-tables: |
    1   net1
```

`initContainer` snippet:

```
  initContainers:
  - name: net-admin
	image: alpine:latest
	securityContext:
	  capabilities:
		add:
		- NET_ADMIN
	command:
	- sh
	- "-c"
	- |
	  set -ex
	  ip route del 10.0.30.0/24 dev net1 scope link  src 10.0.30.30
	  ip route add 10.0.30.0/24 dev net1 src 10.0.30.30 table net1
	  ip route add default via 10.0.30.1 dev net1 table net1
	  ip rule add from 10.0.30.30/32 table net1
	  ip rule add to 10.0.30.30/32 table net1
	volumeMounts:
	- name: routing-tables
	  mountPath: /etc/iproute2
```

The next step is to ensure that `rt_tables` is mounted in all containers which will make use of this route. All routes are shared between containers including the `initContainer` which just set everything up. So long as the routing table is defined, it will be populated upon creation.

The gateway is now properly able to route requests to and from `10.0.30.30` without issue. The only issue is that `net1` can only receive ICMP request, it cannot send them. This shouldn't be an issue though.

For confirmation, I forced traffic from `10.0.30.30` to go through my VPN on the firewall and tested using `curl`:

```
curl --interface eth0 ifconfig.co
70.xx.xx.xx.x
curl --interface net1 ifconfig.co
199.xxx.xxx.xxx
```

All that's left is to have your container bind to ether `net1` or `10.0.30.30` and you will now be able to control the traffic.

Thanks!

**Comment by owengo** [comment]
@Elegant996 thank you for your workaround.
I have a need for multi-homed pods in 2 cases:

1. router / ingress pods for web traffic: for example, I deploy ingress-nginx as a daemonset on an openshift cluster, and I need that the web traffic outputs via a gateway which is not in the sdn network ( external load balancer )
2. email sending pods: I have pods specialized in email sending who need to have 2 things: a default gateway outside the sdn network ( firewall with custom nat configuration ) and a way to configure a SNAT for each pod. For example a set of pods will send emails with a first external ip address and another set will send emails with another external ip address.

So the ability to configure ip route2 routes & rules via annotations would be a great feature.

**Comment by Elegant996** [comment]
@owengo You are welcome but I learned the other week that this is now a cni plugin upstream. Please see [sbr](https://github.com/containernetworking/plugins/tree/master/plugins/meta/sbr) for more info. Thanks!
