### ISSUE TITLE
Make the daemonset installation more flexible and user-friendly

### ISSUE THREAD

**Issue by micw** [intel/multus-cni#219]
Dear multus-cni team,

currently the daemonset deployment method is very static. There's one docker image with a fixed cni config and two k8s daemonset yamls. The configs and yamls in examples/ are more or less unrelated.

I have the following suggestion that I'd like to discuss. The goal is to make the docker image more generic and provide single k8s-yamls fro different use cases. The steps I see are:
- remove all config from the docker image
- add the configs as configmaps to the multus-daemonset.yaml
- merge multus-daemonset.yaml anf flannell-daemonset.yaml so that we have one yaml that reflects a multus+flannel(+portmapping) config
- document in the yaml what is done and why (!)
- move this new yaml to examples/
- refactor the other yamls in examples so that for each use case exactly one yaml exists (containing all required daemonsets and configmaps)
- add more documentation to that examples

I could spend some time on the docker image and the flannel yaml (I already have created some releated PRs #207, #214, #216, #217). But before I continue I'd like to know your opinion about this.

Kind regards,
Michael

**Comment by dougbtv** [comment]
Hey Michael -- huge number of points to talk about here. Thanks for digging into this stuff. Can we cover these in the next maintainers meeting? Number of considerations here.

First two (from my standpoint), that might set the stage and show some history as to why some things have been done as they have been up to this point...

Firstly: Quick-start example installation. When we first put together the daemonset-style installation, it was a large improvement over "having to configure it all yourself". So, almost anything was better than nothing! However, the one advantage of having it be... Rather static -- is that as a first-time user, you have a very opinionated way in which Multus is installed. I think there's room for improvement here -- especially in terms of more flexible configuration, but, also in terms of documentation. However, I don't think we want to do this at the cost of making first-time usage more difficult -- we want to keep at least one very opinionated installation. This will be easier to test, and make sure that first time users are able to get a simple example working. 

Secondarily: Distribution in and proof-of-concept in OpenShift installations. This indeed colored how I had setup the entrypoint script to lay binaries and configuration on disk. Granted, a lot of this was done during a proof-of-concept and can be improved upon. 

Now, point-by-point...

> remove all config from the docker image
> add the configs as configmaps to the multus-daemonset.yaml

The original iteration of this certainly could use some expansion on in terms of how I was figuring one would use it. Mostly, I needed some method of placing configuration files on disk, and did so with a entrypoint script. I think in the future... The config map method is reasonable. I think Kubernetes Operators may control a lot about what's going on there, so, potentially this entrypoint script can be made obsolete.

I also used this method in a number of PoC lab implementations for Multus in OpenShift. 

> merge multus-daemonset.yaml anf flannell-daemonset.yaml so that we have one yaml that reflects a  multus+flannel(+portmapping) config

The reasoning behind having these be separate was to make so that, in theory, you could just apply the Multus daemonset without having to install Flannel, e.g. you already have an existing default network.

I'm still drawn to having these separated. Also, the Flannel daemonset is a modified version of [this upstream one](https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml) -- and it requires periodic maintenance that's unrelated to what's required in the Multus daemonset.

> document in the yaml what is done and why (!)

I propose that we add a new `./doc/` file that's on "Advanced configuration examples" that shows how to take (existing or improved) YAML manifests and setup the config mapping.

> move this new yaml to examples/
> refactor the other yamls in examples so that for each use case exactly one yaml exists (containing all required daemonsets and configmaps)
> add more documentation to that examples

Some of the examples may be out of date -- I think a number of these are from the very first phase of implementation of the NPWG specification. Definitely further documentation would be excellent.

**Comment by micw** [comment]
Hello @dougbtv,
thank you for the great feedback. My list became longer than I expected when starting this issue, probably an open discussion about this is a better way to go.

> Can we cover these in the next maintainers meeting? Number of considerations here.

When and where does this take place? Would it make sense if I'd join for discussion?

> When we first put together the daemonset-style installation, it was a large improvement over "having to configure it all yourself".

This is a very good thing. It helped me a lot to get my 1st setup to work (except the missing portmapping part ^^).

> However, I don't think we want to do this at the cost of making first-time usage more difficult -- we want to keep at least one very opinionated installation

With my approach we could still have the current opinionated installation - the difference is that the configs are in the multus-deamonset.yaml (as configmap) rather than in the docker image. This makes the docker image more flexible without making it more difficult for the first-time user. Honestly I'd stay with that flannel default config for my own server (my home server, single node, I use flannel as default for most containers and an extra bridge config for 2 conatainers that needs their own LAN IP addresses).

> Secondarily: Distribution in and proof-of-concept in OpenShift installations. This indeed colored how I had setup the entrypoint script to lay binaries and configuration on disk

What is special with installation in OpenShift? I have seen that you created an extra docker image for it - what's the difference here?


> .. in theory, you could just apply the Multus daemonset without having to install Flannel ..

True but in this case you'd also had to remove flannel from 70-multus.conf. Meybe we figure out a better way, e.g. a patch to the flannel daemonset that can be applied when we need to update it.

Best regards,
Michael.

**Comment by dougbtv** [comment]
@micw -- we just came across this issue while doing some cleanup, would you care to still join the maintainers meeting to talk about it?

Details on joining here @ https://www.google.com/url?q=https://docs.google.com/document/d/17-vkuoObBFBb6feXNA7tjTaKr-rs8ea0VTnqvlEdCv8/edit%23&sa=D&ust=1585147324046000&usg=AOvVaw2gedn8v2_9skrKw0Ceasmu

**Comment by micw** [comment]
@dougbtv Sure but I need a bit time to catch up with current development. What's the next schedule?

**Comment by micw** [comment]
Btw, with helm3 which does not require server side components (and so would be able to run on a  cluster that has no working CNI), we could also create a helm chart that covers much of the setup flexibility and complexibility.

**Comment by dougbtv** [comment]
Hi @micw -- there was recently a helm-charts repo created as part fo the Network Plumbing Working Group, specifically for a helm-style installation -- @micw would you be willing to work with Mukesh to help create and maintain this repo? 

It's currently part of the NPWG, but, we're trying to work towards making Multus a CNCF project, and we'd probably move that repo under the github namespace when we're able to complete that process. Thanks for all the input time here!

Also -- the meeting connection info can be found here @ https://docs.google.com/document/d/17-vkuoObBFBb6feXNA7tjTaKr-rs8ea0VTnqvlEdCv8/edit#

**Comment by s1061123** [comment]
Now Kubernetes Network Plumbing WG creates the helm-charts so close the issue.

https://github.com/k8snetworkplumbingwg/helm-charts
