### ISSUE TITLE
Bringing up a second interface without IP assigned

### ISSUE THREAD

**Issue by jenifermajella02** [intel/multus-cni#470]
Hi All,

I am trying bring up a second interface in my pod using multus.
But the intially the interface should not have any IP. Is it possible ?

My network definition and pod are below:

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: eth1
spec:
  config: '{
    "type": "bridge",
    "interface": "eth1",
  }'
---
apiVersion: v1
kind: Pod
metadata:
   name: sample
   annotations:
     k8s.v1.cni.cncf.io/networks: '[
            { "name" : "eth1",
              "interface": "eth1" }
    ]'
spec:
   containers:
   - name: sample
     image: sample_generic:v0.16
     command: ["python", "/root/Main.py" ,"trap : TERM INT; sleep infinity & wait"]

But I could see the that the pod ia always in container creating stage.
When I describe pod it says /etc/cni/multus/net.d is not found.
But I could see that I have only this folder structure /etc/cni/net.d/multus.d

KIndly help me to resolve the issue.

**Comment by s1061123** [comment]
Your CNI configuration does not have IP address configuration, hence there is no ip address in your multus interface. This is expected behavior.

```
{
"type": "bridge",
"interface": "eth1",
}
```

To configure IP address in CNI config, you need to configure it as IPAM (IP Address Management).

Please see the following:
https://github.com/containernetworking/cni/blob/master/SPEC.md#network-configuration

In addition, you need to specify which IPAM CNI plugins is used because bridge does not have IPAM functionality. IPAM CNI plugin provides IP address management for the interface/network.

You can find IPAM in following URLs and also you can find other IPAMs in internet:
https://github.com/containernetworking/plugins/tree/master/plugins/ipam
https://github.com/dougbtv/whereabouts

**Comment by jenifermajella02** [comment]
Hi, 

Thanks for the reply. I want the interface without IP. But I am not able to bring up that way. 
Can I bring up a interface without IP?

**Comment by s1061123** [comment]
@jenifermajella02 It depends on each interface plugin, hence if you create CNI plugin that make the interface up without IP, it works. Multus is just a CNI meta plugin and we don't touch network stack, usually.
