### ISSUE TITLE
can't support default gateway for sbr meta plugin

### ISSUE THREAD

**Issue by ryanlyy** [intel/multus-cni#498]
when using the following networkattachment, default gateway can't be added:
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sbr1-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "plugins":
        [
          {
            "type": "macvlan",
            "master": "enp0s8",
            "mode": "bridge",
            "ipam": {
                "type": "static",
                "routes": [
                   { "dst": "0.0.0.0/0", "gw": "200.10.0.1" },
                   { "dst": "1.1.1.0/24", "gw": "200.10.0.1" },
                   { "dst": "2.2.2.0/24", "gw": "200.10.0.1" }
                ]
            }
          },
          {
            "type": "sbr"
          }
        ]
    }'

if course if in "static" config, adding:
        "addresses": [
          {
            "address": "200.10.0.2/24",
            "gateway": "200.10.0.1"
          }
        ],
then default gateway can be added route table 100 (rule). but this results static ip 200.10.0.2 added into every pod. 
So its better to add "gateway" info in pod annotation. but currentlly, it only ips w/o gateway.

**Comment by ryanlyy** [comment]
is there any comments?

Thanks,
Ryan

**Comment by ryanlyy** [comment]
is there any support?

Thanks,
Ryan

**Comment by s1061123** [comment]
>So its better to add "gateway" info in pod annotation. but currentlly, it only ips w/o gateway
I'm not clear what you imagine. Could you please share your expected configuration and output with us?

**Comment by ryanlyy** [comment]
my user case is to add default gateway  w/ sbr meta plugin using NAD? can NAD configuration support it? or how can I configure it?

Thanks,
Ryan

**Comment by s1061123** [comment]
We support 'default-route' option in pod annotation to specify which route should be default route, however, it does not support it with sbr plugin.

Actually 'default-route' option in multus does not add default-route. It just selects default route from routes that is already added by IPAM cni plugin. As following example, 'default-route' in pod annotation and `"routes": [ { "dst": "0.0.0.0/0",..."` are in the yaml. Both are required to change default-route because multus does not add/del specific ip routes. From CNI architecture point of view, IP address management should be done by IPAM plugin and multus follows the policy. 

In case of 'sbr' plugin, you need to configure default route by IPAM plugin (i.e. static), however, currently 'host-local' and 'static' does not specify default route with table option (i.e. `ip route add ... table <rule table name>`)

Currently we suppose that ip address management should be done by IPAM plugin, not multus and 'static'/'host-local' IPAM plugin does not support sbr's route manipulation hence, it does not work.

```
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: centos-gateway-def
spec:
  config: '{
            "cniVersion": "0.3.1",
            "plugins": [
                {
                    "type": "macvlan",
                    (snip)
                     "ipam": {
                        "type": "static",
                        "routes": [
                            {
                              "dst": "0.0.0.0/0",
                              "gw": "10.1.1.1"
                            }
                        ]
                    }
                } ]
        }'
---
apiVersion: v1
kind: Pod
metadata:
  name: centos-gateway
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "centos-gateway-def",
              "ips": [ "10.1.1.103/24" ],
              "default-route": [ "10.1.1.1" ]
            }
    ]'
spec:
  (snip)
```

See for the detail:
https://github.com/k8snetworkplumbingwg/multi-net-spec/tree/master/v1.1
