### ISSUE TITLE
How to set IP for endpoint of service when pod have more one IP ??

### ISSUE THREAD

**Issue by thanhlong9x** [intel/multus-cni#580]
**My Problem**:
I want using sriov network for my endpoint service. Now, This servive set IP eth0 interface for endpoint IPs and I want it use net1 (sriov-net) for endpoint of service.

**My solve**
I config multus-daemonset file in order to using sriov-net as clusterNetwork.

**Result**
My Pods experience anomaly in the pod VF allocation. Pods may not be able to ping other Pods on the same or different networks. This is the error I got:

![image](https://user-images.githubusercontent.com/29721257/98323683-f5350d80-201c-11eb-8e0d-6d7a22c95801.png)

I have heard that sriov is not ready to be the default network.

**Question**
1. Distinguishing for me the difference between the configuration clusterNetwork and defaultNetworks, I do not understand well how these two configurations affect the cluster when creating pod.

2.  I want to assign net1 as the IP of the pod in the endpoint of the respective service. Is there a way to solve it?

**Comment by dougbtv** [comment]
Hrmmm, I'm guessing that whereabouts fails because it can't reach the API due to default network connectivity. Would you mind turning on whereabouts logging (https://github.com/dougbtv/whereabouts#logging-parameters) and showing us what happened? Thanks! 

As for SR-IOV for default network, you might think about opening an issue for SR-IOV specifically @ https://github.com/openshift/sriov-cni

**Comment by thanhlong9x** [comment]
I have configured logging-parameters but not getting the logs of whereabouts. Then I restart the whereabouts and the pod can get the sriov interface without any more errors. Not sure why this is but I'll observe more, I guess this error will come back.

I have a question that can i configure whereabouts to add net-conf parts like the flannel configuration below does.

![image](https://user-images.githubusercontent.com/29721257/98431402-9092b500-20e7-11eb-92e6-3ba0290886b0.png)

Currently, net-attach cannot be routed out of the network configuration configured in NetAttachmentDefinition file, so I want to add cni host-gw to do that.

**Comment by thanhlong9x** [comment]
Hey @dougbtv , I see this error again. I found a lot more cni generated, more than the number of pods running on that node. 

![image](https://user-images.githubusercontent.com/29721257/98915479-8d8b3080-24fc-11eb-8e51-bfbf1b877c47.png)

So I am assuming that the whereabouts have not recovered the IPs allocated to the Pod. Can you tell me about Whereabouts IP recovery mechanism?

**Comment by s1061123** [comment]
One q. Are you going to use multus interface (e.g. net1, net2... of sr-iov) IP address for Kubernetes service?

**Comment by thanhlong9x** [comment]
@s1061123 yes, I want use more one interface for K8s service. I see K8s service auto get IP of eth0, and just one IPv4 (can have IPv6 in dual stack). This is not suitable for apps run separate control and data flow. I think we will need one custom service discovery that allow discovery all IPs on Pods and can select more one IP of Pods when they use multus.

**Comment by s1061123** [comment]
Currently multus does not provide any endpoint (and endpointslice) control for kubernetes service with multus interface IP address because lots of consideration: reachability to multus interface address, load balancing API and so on. Currently [Kubernetes Network Plumbing WG](https://github.com/k8snetworkplumbingwg/community) is start to prototyping/designing it but it is just prototype, not real-use yet.

So if you don't mind it, let me close this issue due to not-support.
