### ISSUE TITLE
interface naming inside the OD

### ISSUE THREAD

**Issue by subrnath** [intel/multus-cni#88]
Inside the POF, currently interfaces names are eth0, net0, net1 , net2 .... ( in this order). Some of the VNF expects the the interfaces to have a specific name like eth0, eth1, eth2 ...( in this order). Hence is it possible to allow the VNF to decide the interface name?

For example, we define a CRD of type "Network" and using ipvlan cni.
```
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: <network name>
plugin: ipvlan
args: '[
                {
                "name": <network name>,
                "type": "ipvlan",
                "master": <host interface details>,
                "ipam": {
                        "type": "host-local",
                        "subnet":  CIDR,
                        "rangeStart":  <start ip>,
                        "rangeEnd": <end ip>"
                }
        }
]'
```
can we add a new argument like "interface" which will define the interface name inside the POD?

**Comment by s1061123** [comment]
Currently kubernetes networking plumbing working group is discussing the CRD format, including network interface name configuration.

Could you please take a look into the google doc, Section 4.1.2.1.5?
https://docs.google.com/document/d/1Ny03h6IDVy_e_vmElOqR7UdTPAG_RNydhVE1Kx54kFQ/edit 

Once it finalize, we are going to implement.

**Comment by rkamudhan** [comment]
@subrnath: Team is working on the reference implementation in the `dev` branch https://github.com/intel/multus-cni/tree/dev/network-plumbing-working-group-crd-change as @s1061123 point out.

This branch will be merged to master in 2 or 3 weeks. currently all the features are tested. The issue is tracked in #83 

Please give a try in the workload with `interfaceRequest` in the network annotation, https://github.com/intel/multus-cni/blob/dev/network-plumbing-working-group-crd-change/examples/npwg-demo-1/12_pod_case2.yml

Hope this solve your issue..

**Comment by subrnath** [comment]
Thanks. Yes. this is solving our issue. Current release from https://github.com/intel/multus-cni/releases can be seen as 2.0. What will be the next release?
